### ISSUE TITLE
Tests fail (with Dist::Zilla 6?)

### ISSUE THREAD

**Issue by eserte** [kentnl/Dist-Zilla-App-Command-dumpwith#1]
See subject. A sample fail report: http://www.cpantesters.org/cpan/report/d43e3bac-160c-11e6-9eec-8e58c2f7efac

**Comment by kentfredric** [comment]
Yep. Dzil 6 alright.

Reduced test-case shows how Dzil changed arg parsing: 

https://gist.github.com/kentfredric/7163c8b8dc0bcef4c8498c95f45d490e

The important part being how my API Is:

```
dzil dumpwith -VersionProvider
```

Which was previously fine, but ... since  6.000, `-V` as a parameter to plugins is now "Verbose", or something. 

So the only way I can continue to have this working is to entirely change my API, or find some dark way to poke dzil's guts and stop it doing that.

 :(
